/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
u Calculate e
Time Limit: 1000MS		Memory Limit: 10000K
Total Submissions: 15946		Accepted: 9593		Special Judge
Description

A simple mathematical formula for e is 
e=Σ0<=i<=n1/i!

where n is allowed to go to infinity. This can actually yield very accurate approximations of e using relatively small values of n.
Input

No input
Output

Output the approximations of e generated by the above formula for the values of n from 0 to 9. The beginning of your output should appear similar to that shown below.
Sample Input

no input
Sample Output

n e
- -----------
0 1
1 2
2 2.5
3 2.666666667
4 2.708333333
...
 */
public class p1517 {
    public static int factorial(int n){
        if(n == 0 || n == 1)
            return 1;
        else
            return n*factorial(n-1);
    }
    public static void main(String[] args) {
        double[] tab = new double[10];
        for(int i = 0; i <= 9;i++){
            if(i == 0)
                tab[i] = 1;
            else if(i == 1)
                tab[i] = 2;
            else
                tab[i] = (double)tab[i-1] + (double)1/factorial(i);
        }
        System.out.println("n e");
        System.out.println("- -----------");
        for(int i = 0; i <= 1 ; i++){
            System.out.printf("%d %.0f\n",i,tab[i]);
        }
        System.out.printf("2 %.1f\n",tab[2]);
        for(int i = 3; i <= 9 ; i++){
            System.out.printf("%d %.9f\n",i,tab[i]);
        }
    }
}
